# https://github.com/bioconda/bioconda-utils/blob/28a4dda0257b436d881da7717a88d75d6bf3067e/bioconda_utils/bioconda_utils-conda_build_config.yaml
pin_run_as_build:
  m2w64-htslib:
    max_pin: x.x


m2w64_htslib:
  - 1.15.1

channel_sources:
  - conda-forge
