# Strategy:
#
# 1. setup msys2 env with GitHub Action setup-msys2
#    https://github.com/msys2/setup-msys2
#
# 2. Follow David's instructions for static linking by applying patches
#    https://github.com/TileDB-Inc/TileDB-VCF/tree/dlh/sc-24772-msys2-htslib-msvc-tdbvcf-WIP1
#    https://github.com/TileDB-Inc/TileDB-VCF/blob/dlh/sc-24772-msys2-htslib-msvc-tdbvcf-WIP1/libtiledbvcf/cmake/patches/htslib.1.15.1.Makefile.staticlink
#    https://github.com/TileDB-Inc/TileDB-VCF/blob/dlh/sc-24772-msys2-htslib-msvc-tdbvcf-WIP1/libtiledbvcf/cmake/patches/htslib.1.15.1.config.mk.staticlink
name: Static linking with msys2
on:
  push:
    paths:
      - '.github/workflows/msys2-static-linking.yml'
  workflow_dispatch:
jobs:
  htslib:
    name: Statically linked htslib
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    env:
      PACKAGE_VERSION: 1.15.1
      LIBHTS_SOVERSION: 3
      RELEASE_VERSION: 0 # equivalent to conda build number
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
      - name: System information
        run: |
          echo $MSYSTEM
          uname -a
          echo $PATH
      - name: Install dependencies with pacman
        run: |
          pacman -S --noconfirm --needed \
            base-devel \
            mingw-w64-x86_64-toolchain \
            mingw-w64-x86_64-autotools \
            mingw-w64-x86_64-zlib \
            mingw-w64-x86_64-bzip2 \
            mingw-w64-x86_64-xz \
            mingw-w64-x86_64-curl \
            mingw-w64-x86_64-tools-git \
            mingw-w64-x86_64-libdeflate
      - name: Download and extract source htslib tarball
        run: |
          curl -O -L "https://github.com/samtools/htslib/releases/download/${PACKAGE_VERSION}/htslib-${PACKAGE_VERSION}.tar.bz2"
          tar -jxvf htslib-${PACKAGE_VERSION}.tar.bz2
          mv htslib-${PACKAGE_VERSION}/* .
          rmdir htslib-${PACKAGE_VERSION}/
      - name: Build
        run: |
          # trial run
          ./configure
          make
          ls -lh hts-${LIBHTS_SOVERSION}.*
          # [should show]
          # hts-3.def  hts-3.dll  hts-3.lib

          # cleanup
          make clean

          # reconfigure
          ./configure CFLAGS=-DCURL_STATICLIB

          # download patches
          wget https://raw.githubusercontent.com/TileDB-Inc/TileDB-VCF/dlh/sc-24772-msys2-htslib-msvc-tdbvcf-WIP1/libtiledbvcf/cmake/patches/htslib.1.15.1.Makefile.staticlink
          wget https://raw.githubusercontent.com/TileDB-Inc/TileDB-VCF/dlh/sc-24772-msys2-htslib-msvc-tdbvcf-WIP1/libtiledbvcf/cmake/patches/htslib.1.15.1.config.mk.staticlink

          # make backups
          cp Makefile Makefile.orig
          cp config.mk config.mk.orig

          # apply patches
          cp htslib.1.15.1.Makefile.staticlink Makefile
          cp htslib.1.15.1.config.mk.staticlink config.mk

          # build with patches
          make

          ls -lh hts-${LIBHTS_SOVERSION}.*
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Check linking
        shell: powershell
        run: |
          dumpbin /imports hts-${env:LIBHTS_SOVERSION}.dll | findstr /i dll
      - name: Upload .dll as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hts-${{ env.LIBHTS_SOVERSION }}.dll
          path: hts-${{ env.LIBHTS_SOVERSION }}.dll
          retention-days: 14
