# Strategy:
#
# 1. setup msys2 env with GitHub Action setup-msys2
#    https://github.com/msys2/setup-msys2
#
# 2. Follow official installation instructions
#    https://github.com/samtools/htslib/blob/463830bf7de8c4ab731c4d67c49ddc446f498f50/INSTALL#L276
name: Use GitHub Action setup-msys2
on:
  workflow_dispatch:
jobs:
  htslib:
    name: Build htslib with setup-msys2
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - name: System information
        run: |
          echo $MSYSTEM
          uname -a
      - name: Download and extract source htslib tarball
        run: |
          curl -sLO https://github.com/samtools/htslib/releases/download/1.16/htslib-1.16.tar.bz2
          tar xvjf htslib-1.16.tar.bz2
          mv htslib-1.16/* .
          rmdir htslib-1.16/
