# Strategy:
#
# 1. setup msys2 env with GitHub Action setup-msys2
#    https://github.com/msys2/setup-msys2
#
# 2. Follow official installation instructions
#    https://github.com/samtools/htslib/blob/463830bf7de8c4ab731c4d67c49ddc446f498f50/INSTALL#L276
#    https://github.com/samtools/htslib/blob/develop/.appveyor.yml
name: Use GitHub Action setup-msys2
on:
  push:
    paths:
      - '.github/workflows/setup-msys2-action.yml'
  workflow_dispatch:
jobs:
  htslib:
    name: Build htslib with setup-msys2
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - name: System information
        run: |
          echo $MSYSTEM
          uname -a
          echo $PATH
      - name: Download and extract source htslib tarball
        run: |
          curl -sLO https://github.com/samtools/htslib/releases/download/1.16/htslib-1.16.tar.bz2
          tar xvjf htslib-1.16.tar.bz2
          mv htslib-1.16/* .
          rmdir htslib-1.16/
      - name: Install dependencies with pacman
        run: |
          pacman -S --noconfirm --needed \
            base-devel \
            mingw-w64-x86_64-toolchain \
            mingw-w64-x86_64-autotools \
            mingw-w64-x86_64-zlib \
            mingw-w64-x86_64-bzip2 \
            mingw-w64-x86_64-xz \
            mingw-w64-x86_64-curl \
            mingw-w64-x86_64-tools-git \
            mingw-w64-x86_64-libdeflate
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make install
        run: make install
      - name: Confirm installation
        run: |
          which bgzip
          bgzip --version
          which htsfile
          htsfile --version
          which tabix
          tabix --version
